#!/usr/bin/env bash
#MISE wait_for=["text:format"]
#MISE sources=["**/*.md", "**/*.yaml", "**/*.json"]
#MISE outputs={auto = true}

set -ex

prettier --check '**/*.{md,yaml,json}' --ignore-path=.gitignore
markdownlint-cli2 --config ./.config/.markdownlint-cli2.yaml "**/*.md"
yamllint -c .config/.yamllint.yaml .
