project_name: athenaeum
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/athenaeum
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Major }}-amd64"
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/callumkerson/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Major }}-arm64"
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/callumkerson/{{ .ProjectName }}:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Version }}-arm64"
  - name_template: "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Major }}"
    image_templates:
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Major }}-amd64"
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Major }}-arm64"
  - name_template: "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/callumkerson/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64"
  - name_template: "ghcr.io/callumkerson/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/callumkerson/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/callumkerson/{{ .ProjectName }}:latest-arm64"
changelog:
  use: github-native
