# https://taskfile.dev

version: "3"

tasks:
  #unix setup
  setup:
    - brew update
    - brew install go golangci-lint yq hadolint
    - task: setup:imports-reviser
    - task: setup:precommit:install

  setup:imports-reviser:
    cmds:
      - brew tap incu6us/homebrew-tap
      - brew update
      - brew install goimports-reviser
    status:
      - command -v goimports-reviser

  setup:precommit:cli:
    cmds:
      - brew update
      - brew install pre-commit
      - pre-commit install
    status:
      - command -v pre-commit

  setup:precommit:install:
    deps:
      - setup:precommit:cli
    cmds:
      - pre-commit install

  #local tasks
  go:mod-tidy:
    - go mod tidy

  go:fmt:
    - gofmt -l -s -w .

  go:lint:
    - golangci-lint run

  go:isort:
    - goimports-reviser -rm-unused -company-prefixes github.com/CallumKerson -project-name github.com/CallumKerson/Athenaeum -use-cache  -format ./...

  test:
    - go test ./...

  compile:
    desc: "Compiles for the current OS and architecture"
    cmds:
      - go build -ldflags "-s -w -X main.Version={{.VERSION}} -X main.Commit={{.COMMIT}} -X main.Date={{now | date "2006-01-02T15:04:05-0700"}}" -o . ./...
    vars:
      COMMIT:
        sh: git rev-parse HEAD
      VERSION:
        sh: echo "$(git describe --tags)-dev+$(git rev-parse --short HEAD)"

  linux-compile:
    desc: "Compiles for Linux"
    cmds:
      - GOOS=linux go build -ldflags "-s -w" -o . ./...

  tidy:
    desc: "Tidies the go project"
    cmds:
      - task: go:mod-tidy
      - task: go:fmt
      - task: go:isort
      - task: go:lint
      - pre-commit run -a

  build:
    desc: "Builds the go project"
    cmds:
      - task: tidy
      - task: compile

  docker:
    desc: "Build and run container"
    cmds:
      - task: tidy
      - task: linux-compile
      - docker compose up --build
