// Package site turns a library of audiobooks into the tree of files a web
// server publishes directly.
package site

import (
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/CallumKerson/Athenaeum/internal/feed"
	"github.com/CallumKerson/Athenaeum/internal/fsutil"
	"github.com/CallumKerson/Athenaeum/static"
)

const (
	// MarkerName guards the sweep. Only a directory Athenaeum created will ever
	// have files deleted from it, so pointing --out at a home directory cannot
	// destroy anything.
	MarkerName = ".athenaeum-site"

	staticDir = "static"
	indexName = "index.html"
)

var errNotSiteDir = errors.New("output directory is not empty and has no " + MarkerName +
	" marker; refusing to manage it")

// Result summarises what a build did.
type Result struct {
	Feeds   int
	Written int
	Removed int
}

// Build renders every page into root, refreshes the static assets, and removes
// files left over from previous builds.
//
// Files whose contents are unchanged are left untouched so that their
// modification times — and therefore the serving proxy's ETags — stay stable
// across rebuilds.
func Build(root string, content Content, renderer *feed.Renderer, sweep bool, logger *slog.Logger) (Result, error) {
	var result Result

	if err := prepareRoot(root); err != nil {
		return result, err
	}

	// Every path the site should contain after this build, used to decide what to
	// sweep. The marker is included so the sweep never deletes its own guard.
	published := map[string]bool{MarkerName: true}

	writeFile := func(relPath string, contents []byte) error {
		published[relPath] = true
		changed, err := fsutil.WriteIfChanged(filepath.Join(root, filepath.FromSlash(relPath)), contents)
		if err != nil {
			return fmt.Errorf("writing %s: %w", relPath, err)
		}
		if changed {
			result.Written++
			logger.Debug("wrote file", "path", relPath)
		}
		return nil
	}

	for index := range content.Feeds {
		feedPage := &content.Feeds[index]
		contents, err := renderer.Render(feedPage.Books, feedPage.Title, feedPage.Description)
		if err != nil {
			return result, fmt.Errorf("rendering feed %q: %w", feedPage.Title, err)
		}
		result.Feeds++
		for _, relPath := range feedPage.Paths {
			if err := writeFile(relPath, contents); err != nil {
				return result, err
			}
		}
	}

	if err := writeAssets(content, writeFile); err != nil {
		return result, err
	}

	if sweep {
		removed, err := sweepStale(root, published, logger)
		if err != nil {
			return result, err
		}
		result.Removed = removed
	}

	return result, nil
}

// prepareRoot creates the output directory and its marker, refusing to take
// ownership of a directory that already holds someone else's files.
func prepareRoot(root string) error {
	entries, err := os.ReadDir(root)
	switch {
	case errors.Is(err, os.ErrNotExist):
		if err := os.MkdirAll(root, 0o755); err != nil {
			return err
		}
	case err != nil:
		return err
	case len(entries) > 0:
		if _, err = os.Stat(filepath.Join(root, MarkerName)); err != nil {
			return fmt.Errorf("%w: %s", errNotSiteDir, root)
		}
	}
	return fsutil.WriteAtomic(filepath.Join(root, MarkerName),
		[]byte("Generated by athenaeum build. Files here are managed and may be deleted.\n"))
}

// writeAssets publishes the HTML pages, the stylesheet and the embedded iTunes
// artwork the feeds link to.
func writeAssets(content Content, writeFile func(relPath string, contents []byte) error) error {
	assets, err := fs.ReadDir(static.Assets, ".")
	if err != nil {
		return err
	}
	for _, asset := range assets {
		contents, readErr := static.Assets.ReadFile(asset.Name())
		if readErr != nil {
			return readErr
		}
		if err := writeFile(path.Join(staticDir, asset.Name()), contents); err != nil {
			return err
		}
	}

	htmlPages, err := buildHTML(content)
	if err != nil {
		return err
	}
	for _, page := range htmlPages {
		if err := writeFile(page.Path, page.Contents); err != nil {
			return err
		}
	}
	return nil
}

// sweepStale removes files this build did not publish, then prunes the
// directories that leaves empty, so a renamed author does not linger forever.
func sweepStale(root string, published map[string]bool, logger *slog.Logger) (int, error) {
	var stale, dirs []string

	err := filepath.WalkDir(root, func(fullPath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		relPath, relErr := filepath.Rel(root, fullPath)
		if relErr != nil {
			return relErr
		}
		if relPath == "." {
			return nil
		}
		if entry.IsDir() {
			dirs = append(dirs, fullPath)
			return nil
		}
		if !published[filepath.ToSlash(relPath)] {
			stale = append(stale, fullPath)
		}
		return nil
	})
	if err != nil {
		return 0, err
	}

	for _, fullPath := range stale {
		if err := os.Remove(fullPath); err != nil {
			return 0, err
		}
		logger.Debug("removed stale file", "path", fullPath)
	}

	// Deepest first, so a directory emptied by removing its children is itself
	// removable. os.Remove refuses to delete non-empty directories, which is
	// exactly the check we want.
	sort.Slice(dirs, func(i, j int) bool {
		return strings.Count(dirs[i], string(filepath.Separator)) > strings.Count(dirs[j], string(filepath.Separator))
	})
	for _, dir := range dirs {
		_ = os.Remove(dir)
	}

	return len(stale), nil
}
