// Package site turns a library of audiobooks into the tree of files a web
// server publishes directly.
package site

import (
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/CallumKerson/Athenaeum/internal/feed"
	"github.com/CallumKerson/Athenaeum/internal/fsutil"
	"github.com/CallumKerson/Athenaeum/static"
)

const (
	// MarkerName guards the sweep. Only a directory Athenaeum created will ever
	// have files deleted from it, so pointing --out at a home directory cannot
	// destroy anything.
	MarkerName = ".athenaeum-site"
	// manifestName lists every path the last build published. The sweep only
	// removes paths listed there, so files someone else put in the site root —
	// a robots.txt, or a symlink to the media library — are never touched.
	manifestName = ".athenaeum-manifest"

	staticDir = "static"
	indexName = "index.html"
)

var errNotSiteDir = errors.New("output directory is not empty and has no " + MarkerName +
	" marker; refusing to manage it")

// Result summarises what a build did.
type Result struct {
	Feeds   int
	Written int
	Removed int
}

// Build renders every page into root, refreshes the static assets, and removes
// files left over from previous builds.
//
// Files whose contents are unchanged are left untouched so that their
// modification times — and therefore the serving proxy's ETags — stay stable
// across rebuilds.
func Build(root string, content Content, renderer *feed.Renderer, sweep bool, logger *slog.Logger) (Result, error) {
	var result Result

	if err := prepareRoot(root); err != nil {
		return result, err
	}
	previous, err := readManifest(root)
	if err != nil {
		return result, err
	}

	// Every path the site should contain after this build, used to decide what to
	// sweep.
	published := map[string]bool{}

	writeFile := func(relPath string, contents []byte) error {
		published[relPath] = true
		changed, err := fsutil.WriteIfChanged(filepath.Join(root, filepath.FromSlash(relPath)), contents)
		if err != nil {
			return fmt.Errorf("writing %s: %w", relPath, err)
		}
		if changed {
			result.Written++
			logger.Debug("wrote file", "path", relPath)
		}
		return nil
	}

	for index := range content.Feeds {
		feedPage := &content.Feeds[index]
		contents, err := renderer.Render(feedPage.Books, feedPage.Title, feedPage.Description)
		if err != nil {
			return result, fmt.Errorf("rendering feed %q: %w", feedPage.Title, err)
		}
		result.Feeds++
		for _, relPath := range feedPage.Paths {
			if err := writeFile(relPath, contents); err != nil {
				return result, err
			}
		}
	}

	if err := writeAssets(content, writeFile); err != nil {
		return result, err
	}

	if sweep {
		removed, err := sweepStale(root, previous, published, logger)
		if err != nil {
			return result, err
		}
		result.Removed = removed
	} else {
		// Unswept files stay in the manifest, so a later build that does sweep
		// still knows they are its own.
		for relPath := range previous {
			published[relPath] = true
		}
	}

	return result, writeManifest(root, published)
}

// prepareRoot creates the output directory and its marker, refusing to take
// ownership of a directory that already holds someone else's files.
func prepareRoot(root string) error {
	entries, err := os.ReadDir(root)
	switch {
	case errors.Is(err, os.ErrNotExist):
		if err := os.MkdirAll(root, 0o755); err != nil {
			return err
		}
	case err != nil:
		return err
	case len(entries) > 0:
		if _, err = os.Stat(filepath.Join(root, MarkerName)); err != nil {
			return fmt.Errorf("%w: %s", errNotSiteDir, root)
		}
	}
	return fsutil.WriteAtomic(filepath.Join(root, MarkerName),
		[]byte("Generated by athenaeum build. Files here are managed and may be deleted.\n"))
}

// writeAssets publishes the HTML pages, the stylesheet and the embedded iTunes
// artwork the feeds link to.
func writeAssets(content Content, writeFile func(relPath string, contents []byte) error) error {
	assets, err := fs.ReadDir(static.Assets, ".")
	if err != nil {
		return err
	}
	for _, asset := range assets {
		contents, readErr := static.Assets.ReadFile(asset.Name())
		if readErr != nil {
			return readErr
		}
		if err := writeFile(path.Join(staticDir, asset.Name()), contents); err != nil {
			return err
		}
	}

	htmlPages, err := buildHTML(content)
	if err != nil {
		return err
	}
	for _, page := range htmlPages {
		if err := writeFile(page.Path, page.Contents); err != nil {
			return err
		}
	}
	return nil
}

// readManifest returns the paths the previous build published. A site built
// before the manifest existed has none, so nothing is swept until one is written.
func readManifest(root string) (map[string]bool, error) {
	contents, err := os.ReadFile(filepath.Join(root, manifestName))
	if errors.Is(err, os.ErrNotExist) {
		return map[string]bool{}, nil
	}
	if err != nil {
		return nil, err
	}

	paths := map[string]bool{}
	for relPath := range strings.SplitSeq(string(contents), "\n") {
		// A hand-edited manifest must not be able to point the sweep outside root.
		if relPath != "" && filepath.IsLocal(filepath.FromSlash(relPath)) {
			paths[relPath] = true
		}
	}
	return paths, nil
}

func writeManifest(root string, published map[string]bool) error {
	paths := make([]string, 0, len(published))
	for relPath := range published {
		paths = append(paths, relPath)
	}
	sort.Strings(paths)
	_, err := fsutil.WriteIfChanged(filepath.Join(root, manifestName), []byte(strings.Join(paths, "\n")+"\n"))
	return err
}

// sweepStale removes the files the previous build published and this one did
// not, then prunes the directories that leaves empty, so a renamed author does
// not linger forever.
func sweepStale(root string, previous, published map[string]bool, logger *slog.Logger) (int, error) {
	var stale []string
	for relPath := range previous {
		if !published[relPath] {
			stale = append(stale, relPath)
		}
	}
	sort.Strings(stale)

	removed := 0
	for _, relPath := range stale {
		fullPath := filepath.Join(root, filepath.FromSlash(relPath))
		err := os.Remove(fullPath)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return removed, err
		}
		removed++
		logger.Debug("removed stale file", "path", relPath)
		pruneEmptyDirs(root, filepath.Dir(fullPath))
	}
	return removed, nil
}

// pruneEmptyDirs removes dir and its parents up to, but not including, root.
// os.Remove refuses to delete a non-empty directory, which is exactly the check
// we want, so the first failure ends the climb.
func pruneEmptyDirs(root, dir string) {
	for {
		relDir, err := filepath.Rel(root, dir)
		if err != nil || relDir == "." || !filepath.IsLocal(relDir) || os.Remove(dir) != nil {
			return
		}
		dir = filepath.Dir(dir)
	}
}
