[tools]
"github:golangci/golangci-lint" = "2.6.2"
go = "1.25.6"
hk = "latest"
typos = "latest"
rumdl = "latest"
oxfmt = { depends = "aube", "version" = "latest" }
aube = "latest"

[task_config]
includes = ["tasks"]

[tasks.check]
run = "hk check"

[tasks.check-pr]
run = "hk check --from-ref origin/main --to-ref HEAD"

[tasks.check-all]
run = "hk check --all"

[tasks.fix]
run = "hk fix"

[tasks.fix-pr]
run = "hk fix --from-ref origin/main --to-ref HEAD"

[tasks.fix-all]
run = "hk fix --all"

[tasks.test]
description = "Runs all tests"
depends = ["*:test"]

[tasks.ci]
description = "Runs all CI checks - lint and test"
depends = ["check-pr", "test"]
