#!/usr/bin/env bash
#MISE depends=["golang:mod-tidy"]
#MISE sources=["go.mod", "go.sum", "**/*.go"]
#MISE outputs={auto = true}

golangci-lint run --fix --allow-parallel-runners --config ./.config/.golangci.yaml
